using System.Collections;
using System.Collections.Generic;
using TMPro;
using UnityEngine;
using UnityEngine.AI;

public class EnemyAI : MonoBehaviour
{
    
    [SerializeField] float chaseRange = 10f;
    [SerializeField] float turnSpeed = 5f;
    [SerializeField] TextMeshProUGUI zombieCount;


    NavMeshAgent navMeshAgent;
    float distToTarg = Mathf.Infinity;
    bool isProvoked = false;
    EnemyHealth health;
    Transform target;


    void Start()
    {
        navMeshAgent = GetComponent<NavMeshAgent>();
        health = GetComponent<EnemyHealth>();
        target = FindObjectOfType<PlayerHealth>().transform;

    }

    void Update()
    {

        if(health.IsDead())
        {   
            enabled = false;
            navMeshAgent.enabled = false;
            DisplayCount();
        }
        distToTarg = Vector3.Distance(target.position, transform.position);

        if (isProvoked)
        {
            EngageTarget();
        }
        else if (distToTarg <= chaseRange)
        {
            isProvoked = true;
            ChaseTarget();
        }
    }

    private void DisplayCount()
    {
        int currentZombies = 20;
        --currentZombies;
        zombieCount.text = "Zombies Left\n" + currentZombies.ToString();
    }

    public void OnDamageTaken()
    {
        isProvoked = true;
    }

    private void EngageTarget()
    {
        FaceTarget();
        if (distToTarg >= navMeshAgent.stoppingDistance)
        {
            ChaseTarget();
        }

        if (distToTarg <= navMeshAgent.stoppingDistance)
        {
            AttackTarget();
        }
    }

    private void AttackTarget()
    {
        GetComponent<Animator>().SetBool("attack", true);
    }

    private void ChaseTarget()
    {
        GetComponent<Animator>().SetBool("attack", false);
        GetComponent<Animator>().SetTrigger("move");
        navMeshAgent.SetDestination(target.position);
    }

    private void FaceTarget()
    {
        Vector3 direction = (target.position - transform.position).normalized;
        Quaternion lookRotation = Quaternion.LookRotation(new Vector3(direction.x, 0, direction.z));
        transform.rotation = Quaternion.Slerp(transform.rotation, lookRotation, Time.deltaTime * turnSpeed);
    }

    void OnDrawGizmosSelected()
    {
        Gizmos.color = new Color(1, 0, 0, 0.75F);
        Gizmos.DrawWireSphere(transform.position, chaseRange);
    }
}
